### ISSUE TITLE
Display incorrect when pdf body is text only and the text is so long.

### ISSUE THREAD

**Issue by antranvn** [tejpratap46/PDFCreatorAndroid#9]
When pdf body is text only and the text is so long, then it create first blank page.
The second page contains the text but it miss a lot of text, and the third page blank also.

**Comment by antranvn** [comment]
I simulated the issue by this commit in my folk: https://github.com/antranvn/PDFCreatorAndroid/commit/00ad4e38e7169ca775785709d45f2bb819fae168

**Comment by tejpratap46** [comment]
Yes this is a known issue, as we are rendering views and adding view one by one to page until it is full [842px], what will happen if first view is has height >  842px?
Currently only solution is to use htmlToPdf feature of this library, it will render a webview to PDF with proper pagination.
Otherwise you can create chunks of string and Create multiple PDFTextView.

**Comment by tejpratap46** [comment]
Reopen if you have any suggestion.
